# Generated by Django 3.2.4 on 2023-07-09 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20230709_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plain_text_password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='issue',
            name='trans_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 13, 9, 24, 937240)),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 13, 9, 24, 929237)),
        ),
    ]
