# Generated by Django 3.2.4 on 2023-07-09 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20230709_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='notification_status',
        ),
        migrations.AlterField(
            model_name='issue',
            name='trans_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 17, 8, 3, 437306)),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 17, 8, 3, 437306)),
        ),
    ]
